fix: Multiple imports from custom packages generated in separate lines
SamagraX-Stencil/schematics pull request #7
Opened 2024-04-09 08:22 UTC by Savio629

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: https://github.com/SamagraX-Stencil/stencil-cli/issues/11

## What is the new behavior?

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

## Other information

2024-04-09 08:24 UTC, Savio629 commented
// @sooraj1002

2024-04-15 14:51 UTC, Savio629 commented
@sooraj1002

2024-04-16 09:42 UTC, techsavvyash requested changes

2024-04-16 09:42 UTC, techsavvyash commented on src/utils/module-import.declarator.ts
> +    line.startsWith(`import {`) && line.includes(`} from '${options.path}';`)
can we turn this to a regex?

2024-04-16 09:43 UTC, techsavvyash commented on src/utils/module-import.declarator.ts
> +    line.startsWith(`import {`) && line.includes(`} from '${options.path}';`)
also, could you please share a small video showing that this works?

2024-04-16 09:43 UTC, techsavvyash commented on src/utils/module-import.declarator.ts
> +    line.startsWith(`import {`) && line.includes(`} from '${options.path}';`)
also, please include tests in the cli to test out this functionality.

2024-04-17 07:14 UTC, Savio629 commented
@techsavvyash 

https://github.com/SamagraX-Stencil/schematics/assets/91362589/6150811d-fd03-4a22-a9f1-43c32c476377

2024-04-17 07:22 UTC, Savio629 commented
@techsavvyash Can you specify a bit more on what type of test should I write?

2024-04-17 08:23 UTC, techsavvyash commented
> @techsavvyash Can you specify a bit more on what type of test should I write?

try to think of a few cases which this PR must be solving, for example what is a single import from the samagrax-stencil pacakge is present in the file and you need to add a new import from the same package, will it club the imports in that case? 
The demo in the video can be a test case in itself.

2024-04-17 18:05 UTC, Savio629 commented
@techsavvyash When I run npm run test there are some test which fail
![image](https://github.com/SamagraX-Stencil/schematics/assets/91362589/1b9ba8b4-4d2f-4c5c-b475-1624ab9b4d1c)

2024-04-17 18:20 UTC, techsavvyash commented
Could you update the tests?

2024-04-17 18:42 UTC, Savio629 commented
I'm not good with test but I'll try
can you specify me how can i run a specific test file
`npx jest test/utils/module-import.declarator.test.ts`
is this the right way?
![image](https://github.com/SamagraX-Stencil/schematics/assets/91362589/3c280a40-3e7f-4837-a48f-79f4db9ac62d)

2024-04-17 19:54 UTC, Savio629 commented
@techsavvyash 
https://github.com/SamagraX-Stencil/schematics/assets/91362589/e4b7789c-2599-4051-9c0c-e997cc4c6478

The code works well for clubbing imports and also for clubbing imports even those alias is present but fails for 
Test with different quote chars like ' and " in case of already present imports like in case 1.

Am I doing something wrong here or I'll have to fix for quotes case from the code itself?
This are the test that I wrote

``` 
it('should not break if same package already exists', () => {
  const content: string =
      "import { Module } from '@nestjs/common';\n" +
      "import { TestModule } from '@samagra-x/stencil';\n" +
      '\n' +
      '@Module({})\n' +
      'const x = " from ";\n' +
      'console.error(" from ");\n' +
      'export class FooModule {}\n';
    const options: DeclarationOptions = {
      metadata: 'imports',
      name: 'module',
      path: normalize('@samagra-x/stencil'),
      module: normalize('/src/foo/foo.module.ts'),
      symbol: 'Foo',
      isPackage: false
    };
    const declarator = new ModuleImportDeclarator();
    expect(declarator.declare(content, options)).toEqual(
      "import { Module } from '@nestjs/common';\n" +
      "import { TestModule, Foo} from '@samagra-x/stencil';\n" +
        '\n' +
        '@Module({})\n' +
        'const x = " from ";\n' +
        'console.error(" from ");\n' +
        'export class FooModule {}\n',
    );
  });

  it('should not break for different quote chars', () => {
    const content: string =
        "import { Module } from '@nestjs/common';\n" +
        "import { TestModule } from \"@samagra-x/stencil\" ;\n" +
        '\n' +
        '@Module({})\n' +
        'const x = " from ";\n' +
        'console.error(" from ");\n' +
        'export class FooModule {}\n';
      const options: DeclarationOptions = {
        metadata: 'imports',
        name: '@samagra-x/stencil',
        path: normalize('src/foo'),
        module: normalize('/src/foo/foo.module.ts'),
        symbol: 'Foo',
        isPackage: false
      };
      const declarator = new ModuleImportDeclarator();
      expect(declarator.declare(content, options)).toEqual(
        "import { Module } from '@nestjs/common';\n" +
        "import { TestModule, Foo } from \"@samagra-x/stencil\";\n" +
          '\n' +
          '@Module({})\n' +
          'const x = " from ";\n' +
          'console.error(" from ");\n' +
          'export class FooModule {}\n',
      );
    });

    it('should not break if alias is present', () => {
      const content: string =
          "import { Module } from '@nestjs/common';\n" +
          "import { TestModule } from '@samagra-x/stencil';\n" +
          '\n' +
          '@Module({})\n' +
          'const x = " from ";\n' +
          'console.error(" from ");\n' +
          'export class FooModule {}\n';
        const options: DeclarationOptions = {
          metadata: 'imports',
          name: 'module',
          path: normalize('@samagra-x/stencil'),
          module: normalize('/src/foo/foo.module.ts'),
          symbol: 'Foo as F',
          isPackage: false
        };
        const declarator = new ModuleImportDeclarator();
        expect(declarator.declare(content, options)).toEqual(
          "import { Module } from '@nestjs/common';\n" +
          "import { TestModule, Foo as F} from '@samagra-x/stencil';\n" +
            '\n' +
            '@Module({})\n' +
            'const x = " from ";\n' +
            'console.error(" from ");\n' +
            'export class FooModule {}\n',
        );
      });  
```

2024-04-18 06:32 UTC, techsavvyash commented
![Screenshot 2024-04-18 at 12 01 46 PM](https://github.com/SamagraX-Stencil/schematics/assets/67280631/f23eabd7-067f-4e30-b10f-5c4cb966fa86)

why is a `./` coming in front of the package name?

2024-04-18 06:41 UTC, Savio629 commented
I too am confused
Can you check if the below test is right?
```
 it('should not break for different quote chars', () => {
    const content: string =
        "import { Module } from '@nestjs/common';\n" +
        "import { TestModule } from \"@samagra-x/stencil\" ;\n" +
        '\n' +
        '@Module({})\n' +
        'const x = " from ";\n' +
        'console.error(" from ");\n' +
        'export class FooModule {}\n';
      const options: DeclarationOptions = {
        metadata: 'imports',
        name: '@samagra-x/stencil',
        path: normalize('src/foo'),
        module: normalize('/src/foo/foo.module.ts'),
        symbol: 'Foo',
        isPackage: false
      };
      const declarator = new ModuleImportDeclarator();
      expect(declarator.declare(content, options)).toEqual(
        "import { Module } from '@nestjs/common';\n" +
        "import { TestModule, Foo } from \"@samagra-x/stencil\";\n" +
          '\n' +
          '@Module({})\n' +
          'const x = " from ";\n' +
          'console.error(" from ");\n' +
          'export class FooModule {}\n',
      );
    });
```

2024-04-21 10:23 UTC, Savio629 commented
@techsavvyash  I have now fix for different quote chars
I have pushed the test file too
You can test the test file using the below command
`npx jest module-import.declarator.test.ts --config jest.json`

2024-04-22 03:25 UTC, techsavvyash approved these changes
LGTM

2024-04-22 03:26 UTC, merged